### ISSUE TITLE
Export action exports multiple products

### ISSUE THREAD

**Issue by peterjaap** [danslo/ProductMaintenance#1]
When I export a product with the sku 'Eurostar', it exports a CSV with two products; the 'Eurostar' product and the 'Eurostar Sense' product. It seems the filtering used is a 'contains' or maybe a 'starts with' filter, instead of an exact match.

**Comment by danslo** [comment]
Looks like we can't filter on product_id or entity_id, and ``sku`` is seen as ``FILTER_TYPE_INPUT`` and therefore always filtered using a LIKE.

Not sure how to properly fix this yet.

**Comment by danslo** [comment]
We also can't, for example, (temporarily) override ``public static function getAttributeFilterType`` because it's static. Hmmm.
