### ISSUE TITLE
Class 'League\Csv\Reader' not found

### ISSUE THREAD

**Issue by tudn9x** [danslo/ProductMaintenance#4]
Hi, I faced with this error when I click import. Could you please check?
Error: Class 'League\Csv\Reader' not found in /var/www/html/magento/2110/app/code/Rubic/ProductMaintenance/Controller/Adminhtml/Product/Import.php on line 60

**Comment by danslo** [comment]
You didn't install the project using composer, and therefore didn't get ``"league/csv": "^9.1.2"`` dependency.

**Comment by tudn9x** [comment]
Oh, yes, I'm sorry. Thank you very much.
