### ISSUE TITLE
Click to export and nothing downloaded

### ISSUE THREAD

**Issue by tudn9x** [danslo/ProductMaintenance#5]
Hi, when I click export in product edit page. After page reloaded, nothing to download. Could you please check?
Thank you very much.

**Comment by danslo** [comment]
It won't download anything, it will put a CSV file in specific directory specified by configuration. Default location is ``/tmp/<sku of the product>``.

**Comment by tudn9x** [comment]
I think it maybe put into var folder. I found a file with name: importexport_5aab8c05f0bf1.
I right?

**Comment by danslo** [comment]
That's just a temporary file used by Magento 2, to generate the CSV. The actual file that is used for exporting/importing will go into a specific folder specified by configuration. Default location is ``/tmp/<sku of the product>``.

**Comment by tudn9x** [comment]
Thank you very much.
